# GENERAL DEFINITIONS

help_menu: "
  - Every page (except for the very first one) needs a password.

  - If you solve the riddle, you will get the password to the next page.

  - This page uses a session. You can switch between pages, but if you reload it, you will get a new session.
  "
page_title: "Xmas Hacking"
page_icon: "🎄"


# DEFINITION OF THE PAGE CONTENTS

page0:
  is_start: True
  is_end: False
  title: "Haddaway's quest"
  text: "Buckle up for some Eurodance!"
  image: "<img src=https://www.musicbusinessworldwide.com/files/2024/03/Haddaway-%E2%80%93-%E2%80%98What-Is-Love-cover-1992-%C2%A9-BMG-e1709803645198.jpg width=500/>"
  question: "# What is love?
    
    **Baby don't hurt...**
    "
  answer: "me"
  next_page_password: "one"



page1:
  is_start: False
  is_end: False
  title: "Bob Dylan's quest"
  text: "The master singer songwriter has the following question for you"
  image: "<img src=https://wallpapers.com/images/featured-full/bob-dylan-9xn7068n0xu77d6l.jpg width=400/>"
  question: "
    ---

    ## How many roads must a man walk..."
  answer: "down"
  next_page_password: "two"



page2:
  is_start: False
  is_end: False
  title: "AC↯DC's quest"
  text: "The band the has redefined rock has the following question for you"
  image: "<img src=https://www.byte.fm/media/artists/ACDC.JPG width=500/>"
  question: "## I'm on a hiiiiighway to..."
  answer: "hell"
  next_page_password: "three"


page3:
  is_start: False
  is_end: False
  title: "Falco's quest"
  text: "He, who needs no introduction has the following question for you"
  image: "<img src=https://www.sueddeutsche.de/2022/06/21/f63b76eb-bdf4-43d3-bbda-2543f2b799af.jpeg height=400/>"
  question: "
    Er war Superstar
    <br>
    Er war populär
    <br>
    Er war so exaltiert
    <br>
    Because er hatte Flair
    <br>
    Er war ein Virtuose
    <br>
    War 'n Rockidol
    <br>
    Und alles rief
    <br>
    ***Come and rock me...***
    "
  answer: "Amadeus"
  next_page_password: "four"


page4:
  is_start: False
  is_end: False
  title: "Charizard's quest"
  text: "He who has the strongest will of them all wants to know the following from you"
  image: "<img src=https://cdn.moviepilot.de/files/c95a2dfb2a049d425995543450af5d8dc54b1717ab7916a37600c5f8f68b/fill/1200/576/glurak.jpg width=500/>"
  question: "## What is the best element int the world?"
  answer: "Fire"
  next_page_password: "five"


page5:
  is_start: False
  is_end: True
  title: "You did it!"
  text: "### You crazy son of a bitch!"
  image: "<img src=https://i.imgur.com/8EOthJt.jpeg width=500/>"
  question: ""
  answer: ""
  next_page_password: ""